org: weibin
app: petrolscraper
service: petrolscraper

frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-1

functions:
  rateHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(10 minute)
  cronHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      - schedule: cron(0/10 * ? * MON-FRI *)
