org: weibin
app: petrolscraper
service: petrolscraper

frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-1

functions:
  rateHandler:
    handler: handler.main
    events:
      # Invoke Lambda function every minute
      - schedule: rate(2 hours)
  # cronHandler:
  #   handler: handler.main
  #   events:
  #     # Invoke Lambda function every 2nd minute from Mon-Fri
  #     - schedule: cron(0/10 * ? * MON-FRI *)
